// auth types
export const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

// player types
export const FETCH_PLAYERS_REQUEST = 'FETCH_PLAYERS_REQUEST';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAILURE = 'FETCH_PLAYERS_FAILURE';

export const FETCH_PLAYER_REQUEST = 'FETCH_PLAYER_REQUEST';
export const FETCH_PLAYER_SUCCESS = 'FETCH_PLAYER_SUCCESS';
export const FETCH_PLAYER_FAILURE = 'FETCH_PLAYER_FAILURE';

export const FETCH_POST_PLAYER_REQUEST = 'FETCH_POST_PLAYER_REQUEST';
export const FETCH_POST_PLAYER_SUCCESS = 'FETCH_POST_PLAYER_SUCCESS';
export const FETCH_POST_PLAYER_FAILURE = 'FETCH_POST_PLAYER_FAILURE';

// generator types
export const GENERATOR_PLAYER_SELECT  = 'GENERATOR_PLAYER_SELECT';
export const GENERATOR_SELECT_RESET   = 'GENERATOR_SELECT_RESET';
export const GENERATOR_RUN            = 'GENERATOR_RUN';
export const GENERATOR_RESULT_RESET   = 'GENERATOR_RESULT_RESET';
export const GENERATOR_SAVE_REQUEST   = 'GENERATOR_SAVE_REQUEST';
export const GENERATOR_SAVE_FAILURE   = 'GENERATOR_SAVE_FAILURE';
export const GENERATOR_SAVE_SUCCESS   = 'GENERATOR_SAVE_SUCCESS';

// playday types
export const FETCH_PLAYDAYS_REQUEST = 'FETCH_PLAYDAYS_REQUEST';
export const FETCH_PLAYDAYS_SUCCESS = 'FETCH_PLAYDAYS_SUCCESS';
export const FETCH_PLAYDAYS_FAILURE = 'FETCH_PLAYDAYS_FAILURE';

export const FETCH_PLAYDAY_REQUEST = 'FETCH_PLAYDAY_REQUEST';
export const FETCH_PLAYDAY_SUCCESS = 'FETCH_PLAYDAY_SUCCESS';
export const FETCH_PLAYDAY_FAILURE = 'FETCH_PLAYDAY_FAILURE';
